# Generated by Django 2.1.1 on 2018-10-10 08:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField(blank=True, null=True, verbose_name='mobile No.')),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.TextField(max_length=500)),
                ('author_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gndu.Authors')),
            ],
        ),
    ]
